type OneTimeOnlyMoveFlags = {
  humanPawnAInitialMoveEligible: boolean;
  humanPawnBInitialMoveEligible: boolean;
  humanPawnCInitialMoveEligible: boolean;
  humanPawnDInitialMoveEligible: boolean;
  humanPawnEInitialMoveEligible: boolean;
  humanPawnFInitialMoveEligible: boolean;
  humanPawnGInitialMoveEligible: boolean;
  humanPawnHInitialMoveEligible: boolean;
  aiPawnAInitialMoveEligible: boolean;
  aiPawnBInitialMoveEligible: boolean;
  aiPawnCInitialMoveEligible: boolean;
  aiPawnDInitialMoveEligible: boolean;
  aiPawnEInitialMoveEligible: boolean;
  aiPawnFInitialMoveEligible: boolean;
  aiPawnGInitialMoveEligible: boolean;
  aiPawnHInitialMoveEligible: boolean;
  humanCastleRookAEligible: boolean;
  humanCastleRookBEligible: boolean;
  aiCastleRookAEligible: boolean;
  aiCastleRookBEligible: boolean;
  humanPawnAEnPassantEligible: boolean;
  humanPawnBEnPassantEligible: boolean;
  humanPawnCEnPassantEligible: boolean;
  humanPawnDEnPassantEligible: boolean;
  humanPawnEEnPassantEligible: boolean;
  humanPawnFEnPassantEligible: boolean;
  humanPawnGEnPassantEligible: boolean;
  humanPawnHEnPassantEligible: boolean;
  aiPawnAEnPassantEligible: boolean;
  aiPawnBEnPassantEligible: boolean;
  aiPawnCEnPassantEligible: boolean;
  aiPawnDEnPassantEligible: boolean;
  aiPawnEEnPassantEligible: boolean;
  aiPawnFEnPassantEligible: boolean;
  aiPawnGEnPassantEligible: boolean;
  aiPawnHEnPassantEligible: boolean;
};

export default OneTimeOnlyMoveFlags;
